### ISSUE TITLE
Changing consult line with up/down keys works, but mouse click ignored

### ISSUE THREAD

**Issue by sjsepan3** [clearfeld/vscode-search-replace-inplace-commands#3]
line that is target of mouse shows highlights on hover, but left-click does not change active line

v0.0.4

Dev Tools | Console: no log output on key or mouse action described above

**Comment by clearfeld** [comment]
Mouse click currently isn't implemented, I'll add this enhancement. Most likely with a configuration option so its possible to decide whether or not click should go to the selection and close the panel or simply go to the selection.

**Comment by clearfeld** [comment]
Added mouse click support with a configuration option (deployed in version v0.0.5).

The behavior can be customized with the following configuration value `"clearfeld-sri-commands.ConslutLine_MouseClickBehaviour"`.

Options are as follows:
```
Close on selection - Clicking on a result will move to it, and close (exit) the panel.
Enabled            - Clicking on a result will move to it, but leave the panel open.
Disabled           - Mouse click does nothing.
```

Default value is set to `Enabled`.
